# 사이트 기본 설정
title: "바둑 기록실"
description: "바둑 공부 링크, 일정, 대회 정보 모음"
theme: minima
url: "https://broryda.github.io"
baseurl: ""   # 그대로 두세요

# 빌드 관련
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/

# 포스트 출력 허용
collections:
  posts:
    output: true

# 카테고리별 정렬 옵션
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post

# 네비게이션 메뉴 (선택사항)
minima:
  skin: classic
  social_links:
    github: broryda
    email: your@email.com

# 블로그 설정
show_excerpts: true
paginate: 10
paginate_path: "/page:num/"

timezone: Asia/Seoul   # 권장: 서버/로컬 시간차 방지
future: true           # 미래 날짜 글도 빌드에 포함

# ... 기존 설정 위/아래 어느 곳이든 들어가면 됨
collections:
  board:
    output: true
    permalink: /board/:title/

defaults:
  - scope:
      path: ""
      type: board
    values:
      layout: post   # 혹은 'page'로 바꿔도 됨(아래 레이아웃 설명 참고)
      category: board
